# Generated by Django 3.2.6 on 2022-02-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductDetail',
            new_name='productDetail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductImage',
            new_name='productImage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='productName',
        ),
    ]
