# Generated by Django 3.2.6 on 2022-02-07 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamProfile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
