# Generated by Django 3.2.6 on 2022-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_team_teamprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamProfile', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
