# Generated by Django 3.2.6 on 2022-02-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0008_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='teamProfile',
            new_name='customerProfile',
        ),
    ]
