# Generated by Django 3.2.6 on 2022-02-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0009_rename_teamprofile_customer_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='localProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamProfile', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
