# Generated by Django 3.2.6 on 2022-02-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0010_localproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localproduct',
            old_name='teamProfile',
            new_name='localProductimage',
        ),
    ]
