# Generated by Django 3.2.6 on 2022-02-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0012_specialproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerProfile',
        ),
    ]
