# Generated by Django 3.2.6 on 2022-02-20 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0015_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='FoodApp.customer'),
            preserve_default=False,
        ),
    ]

