# Generated by Django 3.2.6 on 2022-03-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0024_alter_reviewrating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('comboPackage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.combopackage')),
                ('localProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.localproduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.product')),
                ('specialProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.specialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.customer')),
            ],
        ),
    ]
