# Generated by Django 3.2.6 on 2022-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0026_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('cusineType', models.CharField(choices=[('Indian', 'Indian'), ('Chinise', 'Chinise'), ('Italian', 'Italian'), ('Continental', 'Continental'), ('Italian', 'Italian')], max_length=30)),
                ('cusineName', models.CharField(max_length=30)),
                ('ingridents1', models.CharField(max_length=30)),
                ('ingridents2', models.CharField(max_length=30)),
                ('ingridents3', models.CharField(max_length=30)),
                ('recipeDetail', models.TextField()),
            ],
        ),
    ]
