# Generated by Django 3.2.6 on 2022-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0027_customizemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='localproduct',
            name='Detail',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='localproduct',
            name='productType',
            field=models.CharField(choices=[('LocalProduct', 'LocalProduct'), ('SpecialProduct', 'SpecialProduct'), ('EditProduct', ' EditProduct'), ('ComboPackage', 'ComboPackage')], default=1, max_length=30),
        ),
    ]
