# Generated by Django 3.2.6 on 2022-03-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0029_localproduct_actualprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='comboPackage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='specialProduct',
        ),
    ]
