# Generated by Django 3.2.6 on 2022-04-01 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodApp', '0031_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNo', models.CharField(choices=[('Table No 1', 'Table No 1'), ('Table No 2', 'Table No 2'), ('Table No 3', 'Table No 3'), ('Table No 4', 'Table No 4'), ('Table No 5', 'Table No 5'), ('Table No 6', 'Table No 6'), ('Table No 7', 'Table No 7'), ('Table No 8', 'Table No 8'), ('Table No 9', 'Table No 9'), ('Table No 10', 'Table No 10')], max_length=50)),
                ('date', models.DateField()),
                ('selecthour', models.CharField(choices=[('9AM To 11AM', '9AM To 11AM'), ('12AM To 2PM', '12AM To 2PM'), ('3PM To 5PM', '3PM To 5PM'), ('6PM To 8PM', '6PM To 8PM')], max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('person', models.CharField(choices=[('1 Person', '1 Person'), ('2 Person', '2 Person'), ('3 Person', '3 Person'), ('4 Person', '4 Person'), ('5 Person', '5 Person'), ('Larger Party', 'Larger party')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
