# Generated by Django 3.2.6 on 2022-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0032_reservetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizemenu',
            name='cusineType',
            field=models.CharField(max_length=30),
        ),
    ]
