# Generated by Django 3.2.6 on 2022-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0033_alter_customizemenu_cusinetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='person',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='selecthour',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='tableNo',
            field=models.CharField(max_length=50),
        ),
    ]
