# Generated by Django 3.2.6 on 2022-04-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0034_auto_20220401_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetable',
            name='user',
        ),
    ]
