# Generated by Django 3.2.6 on 2022-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0035_remove_reservetable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='person',
            field=models.CharField(choices=[('1 Person', '1 Person'), ('2 Person', '2 Person'), ('3 Person', '3 Person'), ('4 Person', '4 Person'), ('5 Person', '5 Person'), ('Larger Party', 'Larger party')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='selecthour',
            field=models.CharField(choices=[('9AM To 11AM', '9AM To 11AM'), ('12AM To 2PM', '12AM To 2PM'), ('3PM To 5PM', '3PM To 5PM'), ('6PM To 8PM', '6PM To 8PM')], max_length=50),
        ),
    ]
